---
- name: Install curl package (Debian based)
  action: apt pkg='curl' state=installed
  when: "'$ansible_pkg_mgr' == 'apt'"
    
- name: Install curl package (RedHat based)
  action: yum name='curl' state=installed
  when: "'$ansible_pkg_mgr' == 'yum'"

- name: Check if JumpCloud is already installed
  shell: "[ -d /opt/jc ] && echo 'Found' || echo ''"
  register: jc_installed

- name: Update time
  shell: "ntpdate -u pool.ntp.org"
  ignore_errors: yes
  when: "not jc_installed.stdout"

- name: Install JumpCloud
  shell: "curl --header 'x-connect-key: 485201915b44f3bde090f158c6967f6ce149ff5f' https://kickstart.jumpcloud.com/Kickstart | sudo bash"
  ignore_errors: yes
  when: "not jc_installed.stdout"

- service:
    name: jcagent
    state: restarted